# Generated by Django 5.2 on 2026-03-30 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('dbs', 'DBS Certificate'), ('nmc', 'NMC Certificate'), ('bls', 'BLS / CPR'), ('manual_handling', 'Manual Handling'), ('infection_control', 'Infection Control'), ('rtw', 'Right to Work'), ('passport', 'Passport / ID'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('issued_by', models.CharField(blank=True, max_length=200)),
                ('issued_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('expiring', 'Expiring Soon'), ('expired', 'Expired')], default='valid', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workers.worker')),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
    ]
