# Generated by Django 5.2 on 2026-03-30 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=200)),
                ('nhs_band', models.CharField(choices=[('2', 'Band 2'), ('3', 'Band 3'), ('5', 'Band 5'), ('6', 'Band 6'), ('7', 'Band 7'), ('8a', 'Band 8a')], max_length=5)),
                ('nmc_pin', models.CharField(help_text='NMC registration number e.g. 21A3847E', max_length=20, unique=True)),
                ('right_to_work', models.CharField(choices=[('uk_citizen', 'UK Citizen'), ('eu_settled', 'EU Settled'), ('work_visa', 'Work Visa'), ('other', 'Other')], max_length=50)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated, e.g. ICU, ACLS, Ventilator')),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_shift', 'On Shift'), ('off', 'Off')], default='available', max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('shifts_completed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
